// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package database

import (
	"context"
)

const addItem = `-- name: AddItem :one
INSERT INTO items(
    name, created_at, updated_at
) VALUES(
?1, ?2, ?2
) RETURNING id, name, created_at, updated_at
`

type AddItemParams struct {
	Name string
	Time int64
}

func (q *Queries) AddItem(ctx context.Context, arg AddItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, addItem, arg.Name, arg.Time)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
